"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TicketIdsArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    TICKET_IDS_FIELD_NUMBER: builtins.int
    @property
    def ticket_ids(self) -> global___User.TicketIdsArray: ...
    def __init__(
        self,
        *,
        ticket_ids: global___User.TicketIdsArray | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_ticket_ids", b"_ticket_ids", "ticket_ids", b"ticket_ids"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_ticket_ids", b"_ticket_ids", "ticket_ids", b"ticket_ids"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_ticket_ids", b"_ticket_ids"]) -> typing.Literal["ticket_ids"] | None: ...

global___User = User

@typing.final
class UserIngestTextMessageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPERTY_ID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    SENDER_USER_ID_FIELD_NUMBER: builtins.int
    property_id: builtins.str
    text: builtins.str
    sender_user_id: builtins.str
    def __init__(
        self,
        *,
        property_id: builtins.str | None = ...,
        text: builtins.str | None = ...,
        sender_user_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_property_id", b"_property_id", "_sender_user_id", b"_sender_user_id", "_text", b"_text", "property_id", b"property_id", "sender_user_id", b"sender_user_id", "text", b"text"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_property_id", b"_property_id", "_sender_user_id", b"_sender_user_id", "_text", b"_text", "property_id", b"property_id", "sender_user_id", b"sender_user_id", "text", b"text"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_property_id", b"_property_id"]) -> typing.Literal["property_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sender_user_id", b"_sender_user_id"]) -> typing.Literal["sender_user_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_text", b"_text"]) -> typing.Literal["text"] | None: ...

global___UserIngestTextMessageRequest = UserIngestTextMessageRequest

@typing.final
class UserIngestTextMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKET_ID_FIELD_NUMBER: builtins.int
    ticket_id: builtins.str
    def __init__(
        self,
        *,
        ticket_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_ticket_id", b"_ticket_id", "ticket_id", b"ticket_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_ticket_id", b"_ticket_id", "ticket_id", b"ticket_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_ticket_id", b"_ticket_id"]) -> typing.Literal["ticket_id"] | None: ...

global___UserIngestTextMessageResponse = UserIngestTextMessageResponse

@typing.final
class UserIngestVoiceNoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPERTY_ID_FIELD_NUMBER: builtins.int
    AUDIO_URL_FIELD_NUMBER: builtins.int
    SENDER_USER_ID_FIELD_NUMBER: builtins.int
    property_id: builtins.str
    audio_url: builtins.str
    sender_user_id: builtins.str
    def __init__(
        self,
        *,
        property_id: builtins.str | None = ...,
        audio_url: builtins.str | None = ...,
        sender_user_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_audio_url", b"_audio_url", "_property_id", b"_property_id", "_sender_user_id", b"_sender_user_id", "audio_url", b"audio_url", "property_id", b"property_id", "sender_user_id", b"sender_user_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_audio_url", b"_audio_url", "_property_id", b"_property_id", "_sender_user_id", b"_sender_user_id", "audio_url", b"audio_url", "property_id", b"property_id", "sender_user_id", b"sender_user_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_audio_url", b"_audio_url"]) -> typing.Literal["audio_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_property_id", b"_property_id"]) -> typing.Literal["property_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sender_user_id", b"_sender_user_id"]) -> typing.Literal["sender_user_id"] | None: ...

global___UserIngestVoiceNoteRequest = UserIngestVoiceNoteRequest

@typing.final
class UserIngestVoiceNoteResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TICKET_ID_FIELD_NUMBER: builtins.int
    ticket_id: builtins.str
    def __init__(
        self,
        *,
        ticket_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_ticket_id", b"_ticket_id", "ticket_id", b"ticket_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_ticket_id", b"_ticket_id", "ticket_id", b"ticket_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_ticket_id", b"_ticket_id"]) -> typing.Literal["ticket_id"] | None: ...

global___UserIngestVoiceNoteResponse = UserIngestVoiceNoteResponse

@typing.final
class UserListTicketsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TicketsArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class TicketSummary(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            TICKET_ID_FIELD_NUMBER: builtins.int
            PROPERTY_ID_FIELD_NUMBER: builtins.int
            STATUS_FIELD_NUMBER: builtins.int
            SEVERITY_FIELD_NUMBER: builtins.int
            CATEGORY_FIELD_NUMBER: builtins.int
            LAST_ACTION_FIELD_NUMBER: builtins.int
            COST_AUTHORIZED_USD_FIELD_NUMBER: builtins.int
            SNIPPET_FIELD_NUMBER: builtins.int
            ticket_id: builtins.str
            property_id: builtins.str
            status: builtins.str
            severity: builtins.float
            category: builtins.str
            last_action: builtins.str
            cost_authorized_usd: builtins.float
            snippet: builtins.str
            def __init__(
                self,
                *,
                ticket_id: builtins.str | None = ...,
                property_id: builtins.str | None = ...,
                status: builtins.str | None = ...,
                severity: builtins.float | None = ...,
                category: builtins.str | None = ...,
                last_action: builtins.str | None = ...,
                cost_authorized_usd: builtins.float | None = ...,
                snippet: builtins.str | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_category", b"_category", "_cost_authorized_usd", b"_cost_authorized_usd", "_last_action", b"_last_action", "_property_id", b"_property_id", "_severity", b"_severity", "_snippet", b"_snippet", "_status", b"_status", "_ticket_id", b"_ticket_id", "category", b"category", "cost_authorized_usd", b"cost_authorized_usd", "last_action", b"last_action", "property_id", b"property_id", "severity", b"severity", "snippet", b"snippet", "status", b"status", "ticket_id", b"ticket_id"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_category", b"_category", "_cost_authorized_usd", b"_cost_authorized_usd", "_last_action", b"_last_action", "_property_id", b"_property_id", "_severity", b"_severity", "_snippet", b"_snippet", "_status", b"_status", "_ticket_id", b"_ticket_id", "category", b"category", "cost_authorized_usd", b"cost_authorized_usd", "last_action", b"last_action", "property_id", b"property_id", "severity", b"severity", "snippet", b"snippet", "status", b"status", "ticket_id", b"ticket_id"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_category", b"_category"]) -> typing.Literal["category"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_cost_authorized_usd", b"_cost_authorized_usd"]) -> typing.Literal["cost_authorized_usd"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_last_action", b"_last_action"]) -> typing.Literal["last_action"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_property_id", b"_property_id"]) -> typing.Literal["property_id"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_severity", b"_severity"]) -> typing.Literal["severity"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_snippet", b"_snippet"]) -> typing.Literal["snippet"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_status", b"_status"]) -> typing.Literal["status"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_ticket_id", b"_ticket_id"]) -> typing.Literal["ticket_id"] | None: ...

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserListTicketsResponse.TicketsArray.TicketSummary]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[global___UserListTicketsResponse.TicketsArray.TicketSummary] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    TICKETS_FIELD_NUMBER: builtins.int
    @property
    def tickets(self) -> global___UserListTicketsResponse.TicketsArray: ...
    def __init__(
        self,
        *,
        tickets: global___UserListTicketsResponse.TicketsArray | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_tickets", b"_tickets", "tickets", b"tickets"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_tickets", b"_tickets", "tickets", b"tickets"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_tickets", b"_tickets"]) -> typing.Literal["tickets"] | None: ...

global___UserListTicketsResponse = UserListTicketsResponse

@typing.final
class UserQueryBrainRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    PROPERTY_ID_FIELD_NUMBER: builtins.int
    query: builtins.str
    property_id: builtins.str
    def __init__(
        self,
        *,
        query: builtins.str | None = ...,
        property_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_property_id", b"_property_id", "_query", b"_query", "property_id", b"property_id", "query", b"query"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_property_id", b"_property_id", "_query", b"_query", "property_id", b"property_id", "query", b"query"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_property_id", b"_property_id"]) -> typing.Literal["property_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_query", b"_query"]) -> typing.Literal["query"] | None: ...

global___UserQueryBrainRequest = UserQueryBrainRequest

@typing.final
class UserQueryBrainResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class VoiceMemosArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class BrainVoiceMemo(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ID_FIELD_NUMBER: builtins.int
            TEXT_FIELD_NUMBER: builtins.int
            CONTEXT_FIELD_NUMBER: builtins.int
            DATE_FIELD_NUMBER: builtins.int
            RELEVANCE_FIELD_NUMBER: builtins.int
            id: builtins.str
            text: builtins.str
            context: builtins.str
            date: builtins.str
            relevance: builtins.float
            def __init__(
                self,
                *,
                id: builtins.str | None = ...,
                text: builtins.str | None = ...,
                context: builtins.str | None = ...,
                date: builtins.str | None = ...,
                relevance: builtins.float | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_context", b"_context", "_date", b"_date", "_id", b"_id", "_relevance", b"_relevance", "_text", b"_text", "context", b"context", "date", b"date", "id", b"id", "relevance", b"relevance", "text", b"text"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_context", b"_context", "_date", b"_date", "_id", b"_id", "_relevance", b"_relevance", "_text", b"_text", "context", b"context", "date", b"date", "id", b"id", "relevance", b"relevance", "text", b"text"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_context", b"_context"]) -> typing.Literal["context"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_date", b"_date"]) -> typing.Literal["date"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_relevance", b"_relevance"]) -> typing.Literal["relevance"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_text", b"_text"]) -> typing.Literal["text"] | None: ...

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserQueryBrainResponse.VoiceMemosArray.BrainVoiceMemo]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[global___UserQueryBrainResponse.VoiceMemosArray.BrainVoiceMemo] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    @typing.final
    class Sop(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        TITLE_FIELD_NUMBER: builtins.int
        SNIPPET_FIELD_NUMBER: builtins.int
        id: builtins.str
        title: builtins.str
        snippet: builtins.str
        def __init__(
            self,
            *,
            id: builtins.str | None = ...,
            title: builtins.str | None = ...,
            snippet: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_id", b"_id", "_snippet", b"_snippet", "_title", b"_title", "id", b"id", "snippet", b"snippet", "title", b"title"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_id", b"_id", "_snippet", b"_snippet", "_title", b"_title", "id", b"id", "snippet", b"snippet", "title", b"title"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_snippet", b"_snippet"]) -> typing.Literal["snippet"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

    @typing.final
    class HistoricalArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class BrainHistorical(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            TICKET_ID_FIELD_NUMBER: builtins.int
            TITLE_FIELD_NUMBER: builtins.int
            SNIPPET_FIELD_NUMBER: builtins.int
            RELEVANCE_FIELD_NUMBER: builtins.int
            ticket_id: builtins.str
            title: builtins.str
            snippet: builtins.str
            relevance: builtins.float
            def __init__(
                self,
                *,
                ticket_id: builtins.str | None = ...,
                title: builtins.str | None = ...,
                snippet: builtins.str | None = ...,
                relevance: builtins.float | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_relevance", b"_relevance", "_snippet", b"_snippet", "_ticket_id", b"_ticket_id", "_title", b"_title", "relevance", b"relevance", "snippet", b"snippet", "ticket_id", b"ticket_id", "title", b"title"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_relevance", b"_relevance", "_snippet", b"_snippet", "_ticket_id", b"_ticket_id", "_title", b"_title", "relevance", b"relevance", "snippet", b"snippet", "ticket_id", b"ticket_id", "title", b"title"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_relevance", b"_relevance"]) -> typing.Literal["relevance"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_snippet", b"_snippet"]) -> typing.Literal["snippet"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_ticket_id", b"_ticket_id"]) -> typing.Literal["ticket_id"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserQueryBrainResponse.HistoricalArray.BrainHistorical]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[global___UserQueryBrainResponse.HistoricalArray.BrainHistorical] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    VOICE_MEMOS_FIELD_NUMBER: builtins.int
    SOP_FIELD_NUMBER: builtins.int
    HISTORICAL_FIELD_NUMBER: builtins.int
    @property
    def voice_memos(self) -> global___UserQueryBrainResponse.VoiceMemosArray: ...
    @property
    def sop(self) -> global___UserQueryBrainResponse.Sop: ...
    @property
    def historical(self) -> global___UserQueryBrainResponse.HistoricalArray: ...
    def __init__(
        self,
        *,
        voice_memos: global___UserQueryBrainResponse.VoiceMemosArray | None = ...,
        sop: global___UserQueryBrainResponse.Sop | None = ...,
        historical: global___UserQueryBrainResponse.HistoricalArray | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_historical", b"_historical", "_sop", b"_sop", "_voice_memos", b"_voice_memos", "historical", b"historical", "sop", b"sop", "voice_memos", b"voice_memos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_historical", b"_historical", "_sop", b"_sop", "_voice_memos", b"_voice_memos", "historical", b"historical", "sop", b"sop", "voice_memos", b"voice_memos"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_historical", b"_historical"]) -> typing.Literal["historical"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sop", b"_sop"]) -> typing.Literal["sop"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_voice_memos", b"_voice_memos"]) -> typing.Literal["voice_memos"] | None: ...

global___UserQueryBrainResponse = UserQueryBrainResponse

@typing.final
class UserLiveStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TicketsArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class TicketSummary(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            TICKET_ID_FIELD_NUMBER: builtins.int
            PROPERTY_ID_FIELD_NUMBER: builtins.int
            STATUS_FIELD_NUMBER: builtins.int
            SEVERITY_FIELD_NUMBER: builtins.int
            CATEGORY_FIELD_NUMBER: builtins.int
            LAST_ACTION_FIELD_NUMBER: builtins.int
            COST_AUTHORIZED_USD_FIELD_NUMBER: builtins.int
            SNIPPET_FIELD_NUMBER: builtins.int
            ticket_id: builtins.str
            property_id: builtins.str
            status: builtins.str
            severity: builtins.float
            category: builtins.str
            last_action: builtins.str
            cost_authorized_usd: builtins.float
            snippet: builtins.str
            def __init__(
                self,
                *,
                ticket_id: builtins.str | None = ...,
                property_id: builtins.str | None = ...,
                status: builtins.str | None = ...,
                severity: builtins.float | None = ...,
                category: builtins.str | None = ...,
                last_action: builtins.str | None = ...,
                cost_authorized_usd: builtins.float | None = ...,
                snippet: builtins.str | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_category", b"_category", "_cost_authorized_usd", b"_cost_authorized_usd", "_last_action", b"_last_action", "_property_id", b"_property_id", "_severity", b"_severity", "_snippet", b"_snippet", "_status", b"_status", "_ticket_id", b"_ticket_id", "category", b"category", "cost_authorized_usd", b"cost_authorized_usd", "last_action", b"last_action", "property_id", b"property_id", "severity", b"severity", "snippet", b"snippet", "status", b"status", "ticket_id", b"ticket_id"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_category", b"_category", "_cost_authorized_usd", b"_cost_authorized_usd", "_last_action", b"_last_action", "_property_id", b"_property_id", "_severity", b"_severity", "_snippet", b"_snippet", "_status", b"_status", "_ticket_id", b"_ticket_id", "category", b"category", "cost_authorized_usd", b"cost_authorized_usd", "last_action", b"last_action", "property_id", b"property_id", "severity", b"severity", "snippet", b"snippet", "status", b"status", "ticket_id", b"ticket_id"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_category", b"_category"]) -> typing.Literal["category"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_cost_authorized_usd", b"_cost_authorized_usd"]) -> typing.Literal["cost_authorized_usd"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_last_action", b"_last_action"]) -> typing.Literal["last_action"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_property_id", b"_property_id"]) -> typing.Literal["property_id"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_severity", b"_severity"]) -> typing.Literal["severity"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_snippet", b"_snippet"]) -> typing.Literal["snippet"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_status", b"_status"]) -> typing.Literal["status"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_ticket_id", b"_ticket_id"]) -> typing.Literal["ticket_id"] | None: ...

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserLiveStateResponse.TicketsArray.TicketSummary]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[global___UserLiveStateResponse.TicketsArray.TicketSummary] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    @typing.final
    class RecentEventJsonsArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    TICKETS_FIELD_NUMBER: builtins.int
    RECENT_EVENT_JSONS_FIELD_NUMBER: builtins.int
    @property
    def tickets(self) -> global___UserLiveStateResponse.TicketsArray: ...
    @property
    def recent_event_jsons(self) -> global___UserLiveStateResponse.RecentEventJsonsArray: ...
    def __init__(
        self,
        *,
        tickets: global___UserLiveStateResponse.TicketsArray | None = ...,
        recent_event_jsons: global___UserLiveStateResponse.RecentEventJsonsArray | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_recent_event_jsons", b"_recent_event_jsons", "_tickets", b"_tickets", "recent_event_jsons", b"recent_event_jsons", "tickets", b"tickets"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_recent_event_jsons", b"_recent_event_jsons", "_tickets", b"_tickets", "recent_event_jsons", b"recent_event_jsons", "tickets", b"tickets"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_recent_event_jsons", b"_recent_event_jsons"]) -> typing.Literal["recent_event_jsons"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tickets", b"_tickets"]) -> typing.Literal["tickets"] | None: ...

global___UserLiveStateResponse = UserLiveStateResponse

@typing.final
class OpsTicket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MatchedVoiceMemoIdsArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    @typing.final
    class MatchedHistoricalIdsArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    @typing.final
    class SkillArtifact(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class TriggerConditionsArray(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ITEMS_FIELD_NUMBER: builtins.int
            @property
            def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
            def __init__(
                self,
                *,
                items: collections.abc.Iterable[builtins.str] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

        @typing.final
        class InputsRequiredArray(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ITEMS_FIELD_NUMBER: builtins.int
            @property
            def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
            def __init__(
                self,
                *,
                items: collections.abc.Iterable[builtins.str] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

        @typing.final
        class WorkflowStepsArray(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ITEMS_FIELD_NUMBER: builtins.int
            @property
            def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
            def __init__(
                self,
                *,
                items: collections.abc.Iterable[builtins.str] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

        @typing.final
        class PreferredVendorsArray(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ITEMS_FIELD_NUMBER: builtins.int
            @property
            def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
            def __init__(
                self,
                *,
                items: collections.abc.Iterable[builtins.str] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

        @typing.final
        class ApprovalRulesArray(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ITEMS_FIELD_NUMBER: builtins.int
            @property
            def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
            def __init__(
                self,
                *,
                items: collections.abc.Iterable[builtins.str] | None = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

        @typing.final
        class Sources(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            @typing.final
            class BrainLayersUsedArray(google.protobuf.message.Message):
                DESCRIPTOR: google.protobuf.descriptor.Descriptor

                ITEMS_FIELD_NUMBER: builtins.int
                @property
                def items(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
                def __init__(
                    self,
                    *,
                    items: collections.abc.Iterable[builtins.str] | None = ...,
                ) -> None: ...
                def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

            DERIVED_FROM_TICKET_FIELD_NUMBER: builtins.int
            BRAIN_LAYERS_USED_FIELD_NUMBER: builtins.int
            GENERATED_BY_FIELD_NUMBER: builtins.int
            GENERATED_AT_FIELD_NUMBER: builtins.int
            derived_from_ticket: builtins.str
            generated_by: builtins.str
            generated_at: builtins.str
            @property
            def brain_layers_used(self) -> global___OpsTicket.SkillArtifact.Sources.BrainLayersUsedArray: ...
            def __init__(
                self,
                *,
                derived_from_ticket: builtins.str | None = ...,
                brain_layers_used: global___OpsTicket.SkillArtifact.Sources.BrainLayersUsedArray | None = ...,
                generated_by: builtins.str | None = ...,
                generated_at: builtins.str | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_brain_layers_used", b"_brain_layers_used", "_derived_from_ticket", b"_derived_from_ticket", "_generated_at", b"_generated_at", "_generated_by", b"_generated_by", "brain_layers_used", b"brain_layers_used", "derived_from_ticket", b"derived_from_ticket", "generated_at", b"generated_at", "generated_by", b"generated_by"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_brain_layers_used", b"_brain_layers_used", "_derived_from_ticket", b"_derived_from_ticket", "_generated_at", b"_generated_at", "_generated_by", b"_generated_by", "brain_layers_used", b"brain_layers_used", "derived_from_ticket", b"derived_from_ticket", "generated_at", b"generated_at", "generated_by", b"generated_by"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_brain_layers_used", b"_brain_layers_used"]) -> typing.Literal["brain_layers_used"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_derived_from_ticket", b"_derived_from_ticket"]) -> typing.Literal["derived_from_ticket"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_generated_at", b"_generated_at"]) -> typing.Literal["generated_at"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_generated_by", b"_generated_by"]) -> typing.Literal["generated_by"] | None: ...

        SKILL_ID_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        DESCRIPTION_FIELD_NUMBER: builtins.int
        TRIGGER_CONDITIONS_FIELD_NUMBER: builtins.int
        INPUTS_REQUIRED_FIELD_NUMBER: builtins.int
        WORKFLOW_STEPS_FIELD_NUMBER: builtins.int
        PREFERRED_VENDORS_FIELD_NUMBER: builtins.int
        AUTH_CAP_USD_FIELD_NUMBER: builtins.int
        GUEST_VOICE_STYLE_FIELD_NUMBER: builtins.int
        APPROVAL_RULES_FIELD_NUMBER: builtins.int
        SOURCES_FIELD_NUMBER: builtins.int
        skill_id: builtins.str
        name: builtins.str
        description: builtins.str
        auth_cap_usd: builtins.float
        guest_voice_style: builtins.str
        @property
        def trigger_conditions(self) -> global___OpsTicket.SkillArtifact.TriggerConditionsArray: ...
        @property
        def inputs_required(self) -> global___OpsTicket.SkillArtifact.InputsRequiredArray: ...
        @property
        def workflow_steps(self) -> global___OpsTicket.SkillArtifact.WorkflowStepsArray: ...
        @property
        def preferred_vendors(self) -> global___OpsTicket.SkillArtifact.PreferredVendorsArray: ...
        @property
        def approval_rules(self) -> global___OpsTicket.SkillArtifact.ApprovalRulesArray: ...
        @property
        def sources(self) -> global___OpsTicket.SkillArtifact.Sources: ...
        def __init__(
            self,
            *,
            skill_id: builtins.str | None = ...,
            name: builtins.str | None = ...,
            description: builtins.str | None = ...,
            trigger_conditions: global___OpsTicket.SkillArtifact.TriggerConditionsArray | None = ...,
            inputs_required: global___OpsTicket.SkillArtifact.InputsRequiredArray | None = ...,
            workflow_steps: global___OpsTicket.SkillArtifact.WorkflowStepsArray | None = ...,
            preferred_vendors: global___OpsTicket.SkillArtifact.PreferredVendorsArray | None = ...,
            auth_cap_usd: builtins.float | None = ...,
            guest_voice_style: builtins.str | None = ...,
            approval_rules: global___OpsTicket.SkillArtifact.ApprovalRulesArray | None = ...,
            sources: global___OpsTicket.SkillArtifact.Sources | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_approval_rules", b"_approval_rules", "_auth_cap_usd", b"_auth_cap_usd", "_description", b"_description", "_guest_voice_style", b"_guest_voice_style", "_inputs_required", b"_inputs_required", "_name", b"_name", "_preferred_vendors", b"_preferred_vendors", "_skill_id", b"_skill_id", "_sources", b"_sources", "_trigger_conditions", b"_trigger_conditions", "_workflow_steps", b"_workflow_steps", "approval_rules", b"approval_rules", "auth_cap_usd", b"auth_cap_usd", "description", b"description", "guest_voice_style", b"guest_voice_style", "inputs_required", b"inputs_required", "name", b"name", "preferred_vendors", b"preferred_vendors", "skill_id", b"skill_id", "sources", b"sources", "trigger_conditions", b"trigger_conditions", "workflow_steps", b"workflow_steps"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_approval_rules", b"_approval_rules", "_auth_cap_usd", b"_auth_cap_usd", "_description", b"_description", "_guest_voice_style", b"_guest_voice_style", "_inputs_required", b"_inputs_required", "_name", b"_name", "_preferred_vendors", b"_preferred_vendors", "_skill_id", b"_skill_id", "_sources", b"_sources", "_trigger_conditions", b"_trigger_conditions", "_workflow_steps", b"_workflow_steps", "approval_rules", b"approval_rules", "auth_cap_usd", b"auth_cap_usd", "description", b"description", "guest_voice_style", b"guest_voice_style", "inputs_required", b"inputs_required", "name", b"name", "preferred_vendors", b"preferred_vendors", "skill_id", b"skill_id", "sources", b"sources", "trigger_conditions", b"trigger_conditions", "workflow_steps", b"workflow_steps"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_approval_rules", b"_approval_rules"]) -> typing.Literal["approval_rules"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_auth_cap_usd", b"_auth_cap_usd"]) -> typing.Literal["auth_cap_usd"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_guest_voice_style", b"_guest_voice_style"]) -> typing.Literal["guest_voice_style"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_inputs_required", b"_inputs_required"]) -> typing.Literal["inputs_required"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_preferred_vendors", b"_preferred_vendors"]) -> typing.Literal["preferred_vendors"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_skill_id", b"_skill_id"]) -> typing.Literal["skill_id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_sources", b"_sources"]) -> typing.Literal["sources"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_trigger_conditions", b"_trigger_conditions"]) -> typing.Literal["trigger_conditions"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_workflow_steps", b"_workflow_steps"]) -> typing.Literal["workflow_steps"] | None: ...

    @typing.final
    class HistoryArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class HistoryEvent(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            TS_FIELD_NUMBER: builtins.int
            TYPE_FIELD_NUMBER: builtins.int
            PAYLOAD_JSON_FIELD_NUMBER: builtins.int
            ts: builtins.str
            type: builtins.str
            payload_json: builtins.str
            def __init__(
                self,
                *,
                ts: builtins.str | None = ...,
                type: builtins.str | None = ...,
                payload_json: builtins.str | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_payload_json", b"_payload_json", "_ts", b"_ts", "_type", b"_type", "payload_json", b"payload_json", "ts", b"ts", "type", b"type"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_payload_json", b"_payload_json", "_ts", b"_ts", "_type", b"_type", "payload_json", b"payload_json", "ts", b"ts", "type", b"type"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_payload_json", b"_payload_json"]) -> typing.Literal["payload_json"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_ts", b"_ts"]) -> typing.Literal["ts"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_type", b"_type"]) -> typing.Literal["type"] | None: ...

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OpsTicket.HistoryArray.HistoryEvent]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[global___OpsTicket.HistoryArray.HistoryEvent] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    @typing.final
    class DispatchesArray(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class Dispatch(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            ID_FIELD_NUMBER: builtins.int
            VENDOR_ID_FIELD_NUMBER: builtins.int
            COST_ESTIMATE_USD_FIELD_NUMBER: builtins.int
            AUTHORIZED_FIELD_NUMBER: builtins.int
            ETA_ISO_FIELD_NUMBER: builtins.int
            AUTO_ESCALATE_AFTER_SECONDS_FIELD_NUMBER: builtins.int
            ACKNOWLEDGED_FIELD_NUMBER: builtins.int
            ESCALATED_FIELD_NUMBER: builtins.int
            id: builtins.str
            vendor_id: builtins.str
            cost_estimate_usd: builtins.float
            authorized: builtins.bool
            eta_iso: builtins.str
            auto_escalate_after_seconds: builtins.float
            acknowledged: builtins.bool
            escalated: builtins.bool
            def __init__(
                self,
                *,
                id: builtins.str | None = ...,
                vendor_id: builtins.str | None = ...,
                cost_estimate_usd: builtins.float | None = ...,
                authorized: builtins.bool | None = ...,
                eta_iso: builtins.str | None = ...,
                auto_escalate_after_seconds: builtins.float | None = ...,
                acknowledged: builtins.bool | None = ...,
                escalated: builtins.bool | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["_acknowledged", b"_acknowledged", "_authorized", b"_authorized", "_auto_escalate_after_seconds", b"_auto_escalate_after_seconds", "_cost_estimate_usd", b"_cost_estimate_usd", "_escalated", b"_escalated", "_eta_iso", b"_eta_iso", "_id", b"_id", "_vendor_id", b"_vendor_id", "acknowledged", b"acknowledged", "authorized", b"authorized", "auto_escalate_after_seconds", b"auto_escalate_after_seconds", "cost_estimate_usd", b"cost_estimate_usd", "escalated", b"escalated", "eta_iso", b"eta_iso", "id", b"id", "vendor_id", b"vendor_id"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["_acknowledged", b"_acknowledged", "_authorized", b"_authorized", "_auto_escalate_after_seconds", b"_auto_escalate_after_seconds", "_cost_estimate_usd", b"_cost_estimate_usd", "_escalated", b"_escalated", "_eta_iso", b"_eta_iso", "_id", b"_id", "_vendor_id", b"_vendor_id", "acknowledged", b"acknowledged", "authorized", b"authorized", "auto_escalate_after_seconds", b"auto_escalate_after_seconds", "cost_estimate_usd", b"cost_estimate_usd", "escalated", b"escalated", "eta_iso", b"eta_iso", "id", b"id", "vendor_id", b"vendor_id"]) -> None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_acknowledged", b"_acknowledged"]) -> typing.Literal["acknowledged"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_authorized", b"_authorized"]) -> typing.Literal["authorized"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_auto_escalate_after_seconds", b"_auto_escalate_after_seconds"]) -> typing.Literal["auto_escalate_after_seconds"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_cost_estimate_usd", b"_cost_estimate_usd"]) -> typing.Literal["cost_estimate_usd"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_escalated", b"_escalated"]) -> typing.Literal["escalated"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_eta_iso", b"_eta_iso"]) -> typing.Literal["eta_iso"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...
            @typing.overload
            def WhichOneof(self, oneof_group: typing.Literal["_vendor_id", b"_vendor_id"]) -> typing.Literal["vendor_id"] | None: ...

        ITEMS_FIELD_NUMBER: builtins.int
        @property
        def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OpsTicket.DispatchesArray.Dispatch]: ...
        def __init__(
            self,
            *,
            items: collections.abc.Iterable[global___OpsTicket.DispatchesArray.Dispatch] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

    PROPERTY_ID_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    RAW_INPUT_FIELD_NUMBER: builtins.int
    TRANSCRIPT_NATIVE_FIELD_NUMBER: builtins.int
    TRANSCRIPT_EN_FIELD_NUMBER: builtins.int
    DETECTED_LANGUAGE_FIELD_NUMBER: builtins.int
    CATEGORY_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ASSIGNED_TO_FIELD_NUMBER: builtins.int
    COST_AUTHORIZED_USD_FIELD_NUMBER: builtins.int
    MATCHED_SOP_ID_FIELD_NUMBER: builtins.int
    MATCHED_VOICE_MEMO_IDS_FIELD_NUMBER: builtins.int
    MATCHED_HISTORICAL_IDS_FIELD_NUMBER: builtins.int
    SKILL_ARTIFACT_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    SENDER_USER_ID_FIELD_NUMBER: builtins.int
    HISTORY_FIELD_NUMBER: builtins.int
    DISPATCHES_FIELD_NUMBER: builtins.int
    property_id: builtins.str
    source: builtins.str
    raw_input: builtins.str
    transcript_native: builtins.str
    transcript_en: builtins.str
    detected_language: builtins.str
    category: builtins.str
    severity: builtins.float
    status: builtins.str
    assigned_to: builtins.str
    cost_authorized_usd: builtins.float
    matched_sop_id: builtins.str
    created_at: builtins.str
    sender_user_id: builtins.str
    @property
    def matched_voice_memo_ids(self) -> global___OpsTicket.MatchedVoiceMemoIdsArray: ...
    @property
    def matched_historical_ids(self) -> global___OpsTicket.MatchedHistoricalIdsArray: ...
    @property
    def skill_artifact(self) -> global___OpsTicket.SkillArtifact: ...
    @property
    def history(self) -> global___OpsTicket.HistoryArray: ...
    @property
    def dispatches(self) -> global___OpsTicket.DispatchesArray: ...
    def __init__(
        self,
        *,
        property_id: builtins.str | None = ...,
        source: builtins.str | None = ...,
        raw_input: builtins.str | None = ...,
        transcript_native: builtins.str | None = ...,
        transcript_en: builtins.str | None = ...,
        detected_language: builtins.str | None = ...,
        category: builtins.str | None = ...,
        severity: builtins.float | None = ...,
        status: builtins.str | None = ...,
        assigned_to: builtins.str | None = ...,
        cost_authorized_usd: builtins.float | None = ...,
        matched_sop_id: builtins.str | None = ...,
        matched_voice_memo_ids: global___OpsTicket.MatchedVoiceMemoIdsArray | None = ...,
        matched_historical_ids: global___OpsTicket.MatchedHistoricalIdsArray | None = ...,
        skill_artifact: global___OpsTicket.SkillArtifact | None = ...,
        created_at: builtins.str | None = ...,
        sender_user_id: builtins.str | None = ...,
        history: global___OpsTicket.HistoryArray | None = ...,
        dispatches: global___OpsTicket.DispatchesArray | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_assigned_to", b"_assigned_to", "_category", b"_category", "_cost_authorized_usd", b"_cost_authorized_usd", "_created_at", b"_created_at", "_detected_language", b"_detected_language", "_dispatches", b"_dispatches", "_history", b"_history", "_matched_historical_ids", b"_matched_historical_ids", "_matched_sop_id", b"_matched_sop_id", "_matched_voice_memo_ids", b"_matched_voice_memo_ids", "_property_id", b"_property_id", "_raw_input", b"_raw_input", "_sender_user_id", b"_sender_user_id", "_severity", b"_severity", "_skill_artifact", b"_skill_artifact", "_source", b"_source", "_status", b"_status", "_transcript_en", b"_transcript_en", "_transcript_native", b"_transcript_native", "assigned_to", b"assigned_to", "category", b"category", "cost_authorized_usd", b"cost_authorized_usd", "created_at", b"created_at", "detected_language", b"detected_language", "dispatches", b"dispatches", "history", b"history", "matched_historical_ids", b"matched_historical_ids", "matched_sop_id", b"matched_sop_id", "matched_voice_memo_ids", b"matched_voice_memo_ids", "property_id", b"property_id", "raw_input", b"raw_input", "sender_user_id", b"sender_user_id", "severity", b"severity", "skill_artifact", b"skill_artifact", "source", b"source", "status", b"status", "transcript_en", b"transcript_en", "transcript_native", b"transcript_native"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_assigned_to", b"_assigned_to", "_category", b"_category", "_cost_authorized_usd", b"_cost_authorized_usd", "_created_at", b"_created_at", "_detected_language", b"_detected_language", "_dispatches", b"_dispatches", "_history", b"_history", "_matched_historical_ids", b"_matched_historical_ids", "_matched_sop_id", b"_matched_sop_id", "_matched_voice_memo_ids", b"_matched_voice_memo_ids", "_property_id", b"_property_id", "_raw_input", b"_raw_input", "_sender_user_id", b"_sender_user_id", "_severity", b"_severity", "_skill_artifact", b"_skill_artifact", "_source", b"_source", "_status", b"_status", "_transcript_en", b"_transcript_en", "_transcript_native", b"_transcript_native", "assigned_to", b"assigned_to", "category", b"category", "cost_authorized_usd", b"cost_authorized_usd", "created_at", b"created_at", "detected_language", b"detected_language", "dispatches", b"dispatches", "history", b"history", "matched_historical_ids", b"matched_historical_ids", "matched_sop_id", b"matched_sop_id", "matched_voice_memo_ids", b"matched_voice_memo_ids", "property_id", b"property_id", "raw_input", b"raw_input", "sender_user_id", b"sender_user_id", "severity", b"severity", "skill_artifact", b"skill_artifact", "source", b"source", "status", b"status", "transcript_en", b"transcript_en", "transcript_native", b"transcript_native"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_assigned_to", b"_assigned_to"]) -> typing.Literal["assigned_to"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_category", b"_category"]) -> typing.Literal["category"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_cost_authorized_usd", b"_cost_authorized_usd"]) -> typing.Literal["cost_authorized_usd"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_created_at", b"_created_at"]) -> typing.Literal["created_at"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_detected_language", b"_detected_language"]) -> typing.Literal["detected_language"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dispatches", b"_dispatches"]) -> typing.Literal["dispatches"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_history", b"_history"]) -> typing.Literal["history"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_matched_historical_ids", b"_matched_historical_ids"]) -> typing.Literal["matched_historical_ids"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_matched_sop_id", b"_matched_sop_id"]) -> typing.Literal["matched_sop_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_matched_voice_memo_ids", b"_matched_voice_memo_ids"]) -> typing.Literal["matched_voice_memo_ids"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_property_id", b"_property_id"]) -> typing.Literal["property_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_raw_input", b"_raw_input"]) -> typing.Literal["raw_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sender_user_id", b"_sender_user_id"]) -> typing.Literal["sender_user_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_severity", b"_severity"]) -> typing.Literal["severity"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_skill_artifact", b"_skill_artifact"]) -> typing.Literal["skill_artifact"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_source", b"_source"]) -> typing.Literal["source"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_status", b"_status"]) -> typing.Literal["status"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_transcript_en", b"_transcript_en"]) -> typing.Literal["transcript_en"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_transcript_native", b"_transcript_native"]) -> typing.Literal["transcript_native"] | None: ...

global___OpsTicket = OpsTicket

@typing.final
class OpsTicketCreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPERTY_ID_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    RAW_INPUT_FIELD_NUMBER: builtins.int
    TRANSCRIPT_NATIVE_FIELD_NUMBER: builtins.int
    TRANSCRIPT_EN_FIELD_NUMBER: builtins.int
    DETECTED_LANGUAGE_FIELD_NUMBER: builtins.int
    SENDER_USER_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    property_id: builtins.str
    source: builtins.str
    raw_input: builtins.str
    transcript_native: builtins.str
    transcript_en: builtins.str
    detected_language: builtins.str
    sender_user_id: builtins.str
    created_at: builtins.str
    def __init__(
        self,
        *,
        property_id: builtins.str | None = ...,
        source: builtins.str | None = ...,
        raw_input: builtins.str | None = ...,
        transcript_native: builtins.str | None = ...,
        transcript_en: builtins.str | None = ...,
        detected_language: builtins.str | None = ...,
        sender_user_id: builtins.str | None = ...,
        created_at: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_created_at", b"_created_at", "_detected_language", b"_detected_language", "_property_id", b"_property_id", "_raw_input", b"_raw_input", "_sender_user_id", b"_sender_user_id", "_source", b"_source", "_transcript_en", b"_transcript_en", "_transcript_native", b"_transcript_native", "created_at", b"created_at", "detected_language", b"detected_language", "property_id", b"property_id", "raw_input", b"raw_input", "sender_user_id", b"sender_user_id", "source", b"source", "transcript_en", b"transcript_en", "transcript_native", b"transcript_native"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_created_at", b"_created_at", "_detected_language", b"_detected_language", "_property_id", b"_property_id", "_raw_input", b"_raw_input", "_sender_user_id", b"_sender_user_id", "_source", b"_source", "_transcript_en", b"_transcript_en", "_transcript_native", b"_transcript_native", "created_at", b"created_at", "detected_language", b"detected_language", "property_id", b"property_id", "raw_input", b"raw_input", "sender_user_id", b"sender_user_id", "source", b"source", "transcript_en", b"transcript_en", "transcript_native", b"transcript_native"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_created_at", b"_created_at"]) -> typing.Literal["created_at"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_detected_language", b"_detected_language"]) -> typing.Literal["detected_language"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_property_id", b"_property_id"]) -> typing.Literal["property_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_raw_input", b"_raw_input"]) -> typing.Literal["raw_input"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sender_user_id", b"_sender_user_id"]) -> typing.Literal["sender_user_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_source", b"_source"]) -> typing.Literal["source"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_transcript_en", b"_transcript_en"]) -> typing.Literal["transcript_en"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_transcript_native", b"_transcript_native"]) -> typing.Literal["transcript_native"] | None: ...

global___OpsTicketCreateRequest = OpsTicketCreateRequest

@typing.final
class OpsTicketAcknowledgeDispatchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISPATCH_ID_FIELD_NUMBER: builtins.int
    dispatch_id: builtins.str
    def __init__(
        self,
        *,
        dispatch_id: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dispatch_id", b"_dispatch_id", "dispatch_id", b"dispatch_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dispatch_id", b"_dispatch_id", "dispatch_id", b"dispatch_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_dispatch_id", b"_dispatch_id"]) -> typing.Literal["dispatch_id"] | None: ...

global___OpsTicketAcknowledgeDispatchRequest = OpsTicketAcknowledgeDispatchRequest

@typing.final
class OpsTicketDispatchWithEscalationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VENDOR_ID_FIELD_NUMBER: builtins.int
    COST_ESTIMATE_USD_FIELD_NUMBER: builtins.int
    vendor_id: builtins.str
    cost_estimate_usd: builtins.float
    def __init__(
        self,
        *,
        vendor_id: builtins.str | None = ...,
        cost_estimate_usd: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_cost_estimate_usd", b"_cost_estimate_usd", "_vendor_id", b"_vendor_id", "cost_estimate_usd", b"cost_estimate_usd", "vendor_id", b"vendor_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_cost_estimate_usd", b"_cost_estimate_usd", "_vendor_id", b"_vendor_id", "cost_estimate_usd", b"cost_estimate_usd", "vendor_id", b"vendor_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_cost_estimate_usd", b"_cost_estimate_usd"]) -> typing.Literal["cost_estimate_usd"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_vendor_id", b"_vendor_id"]) -> typing.Literal["vendor_id"] | None: ...

global___OpsTicketDispatchWithEscalationRequest = OpsTicketDispatchWithEscalationRequest

@typing.final
class OpsTicketDispatchWithEscalationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISPATCH_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    dispatch_id: builtins.str
    status: builtins.str
    def __init__(
        self,
        *,
        dispatch_id: builtins.str | None = ...,
        status: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_dispatch_id", b"_dispatch_id", "_status", b"_status", "dispatch_id", b"dispatch_id", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_dispatch_id", b"_dispatch_id", "_status", b"_status", "dispatch_id", b"dispatch_id", "status", b"status"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_dispatch_id", b"_dispatch_id"]) -> typing.Literal["dispatch_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_status", b"_status"]) -> typing.Literal["status"] | None: ...

global___OpsTicketDispatchWithEscalationResponse = OpsTicketDispatchWithEscalationResponse

@typing.final
class OpsTicketProposeNewRuleResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RULE_ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    RULE_JSON_FIELD_NUMBER: builtins.int
    LIGHTSPRINT_PROMPT_FIELD_NUMBER: builtins.int
    rule_id: builtins.str
    title: builtins.str
    description: builtins.str
    rule_json: builtins.str
    lightsprint_prompt: builtins.str
    def __init__(
        self,
        *,
        rule_id: builtins.str | None = ...,
        title: builtins.str | None = ...,
        description: builtins.str | None = ...,
        rule_json: builtins.str | None = ...,
        lightsprint_prompt: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_description", b"_description", "_lightsprint_prompt", b"_lightsprint_prompt", "_rule_id", b"_rule_id", "_rule_json", b"_rule_json", "_title", b"_title", "description", b"description", "lightsprint_prompt", b"lightsprint_prompt", "rule_id", b"rule_id", "rule_json", b"rule_json", "title", b"title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_description", b"_description", "_lightsprint_prompt", b"_lightsprint_prompt", "_rule_id", b"_rule_id", "_rule_json", b"_rule_json", "_title", b"_title", "description", b"description", "lightsprint_prompt", b"lightsprint_prompt", "rule_id", b"rule_id", "rule_json", b"rule_json", "title", b"title"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_lightsprint_prompt", b"_lightsprint_prompt"]) -> typing.Literal["lightsprint_prompt"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rule_id", b"_rule_id"]) -> typing.Literal["rule_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_rule_json", b"_rule_json"]) -> typing.Literal["rule_json"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

global___OpsTicketProposeNewRuleResponse = OpsTicketProposeNewRuleResponse

@typing.final
class OpsTicketShowBrainSourcesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class VoiceMemo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        TEXT_FIELD_NUMBER: builtins.int
        CONTEXT_FIELD_NUMBER: builtins.int
        DATE_FIELD_NUMBER: builtins.int
        RELEVANCE_FIELD_NUMBER: builtins.int
        id: builtins.str
        text: builtins.str
        context: builtins.str
        date: builtins.str
        relevance: builtins.float
        def __init__(
            self,
            *,
            id: builtins.str | None = ...,
            text: builtins.str | None = ...,
            context: builtins.str | None = ...,
            date: builtins.str | None = ...,
            relevance: builtins.float | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_context", b"_context", "_date", b"_date", "_id", b"_id", "_relevance", b"_relevance", "_text", b"_text", "context", b"context", "date", b"date", "id", b"id", "relevance", b"relevance", "text", b"text"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_context", b"_context", "_date", b"_date", "_id", b"_id", "_relevance", b"_relevance", "_text", b"_text", "context", b"context", "date", b"date", "id", b"id", "relevance", b"relevance", "text", b"text"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_context", b"_context"]) -> typing.Literal["context"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_date", b"_date"]) -> typing.Literal["date"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_relevance", b"_relevance"]) -> typing.Literal["relevance"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_text", b"_text"]) -> typing.Literal["text"] | None: ...

    @typing.final
    class Sop(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        TITLE_FIELD_NUMBER: builtins.int
        SNIPPET_FIELD_NUMBER: builtins.int
        id: builtins.str
        title: builtins.str
        snippet: builtins.str
        def __init__(
            self,
            *,
            id: builtins.str | None = ...,
            title: builtins.str | None = ...,
            snippet: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_id", b"_id", "_snippet", b"_snippet", "_title", b"_title", "id", b"id", "snippet", b"snippet", "title", b"title"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_id", b"_id", "_snippet", b"_snippet", "_title", b"_title", "id", b"id", "snippet", b"snippet", "title", b"title"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_id", b"_id"]) -> typing.Literal["id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_snippet", b"_snippet"]) -> typing.Literal["snippet"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

    @typing.final
    class Historical(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TICKET_ID_FIELD_NUMBER: builtins.int
        TITLE_FIELD_NUMBER: builtins.int
        SNIPPET_FIELD_NUMBER: builtins.int
        RELEVANCE_FIELD_NUMBER: builtins.int
        ticket_id: builtins.str
        title: builtins.str
        snippet: builtins.str
        relevance: builtins.float
        def __init__(
            self,
            *,
            ticket_id: builtins.str | None = ...,
            title: builtins.str | None = ...,
            snippet: builtins.str | None = ...,
            relevance: builtins.float | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_relevance", b"_relevance", "_snippet", b"_snippet", "_ticket_id", b"_ticket_id", "_title", b"_title", "relevance", b"relevance", "snippet", b"snippet", "ticket_id", b"ticket_id", "title", b"title"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_relevance", b"_relevance", "_snippet", b"_snippet", "_ticket_id", b"_ticket_id", "_title", b"_title", "relevance", b"relevance", "snippet", b"snippet", "ticket_id", b"ticket_id", "title", b"title"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_relevance", b"_relevance"]) -> typing.Literal["relevance"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_snippet", b"_snippet"]) -> typing.Literal["snippet"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_ticket_id", b"_ticket_id"]) -> typing.Literal["ticket_id"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

    VOICE_MEMO_FIELD_NUMBER: builtins.int
    SOP_FIELD_NUMBER: builtins.int
    HISTORICAL_FIELD_NUMBER: builtins.int
    @property
    def voice_memo(self) -> global___OpsTicketShowBrainSourcesResponse.VoiceMemo: ...
    @property
    def sop(self) -> global___OpsTicketShowBrainSourcesResponse.Sop: ...
    @property
    def historical(self) -> global___OpsTicketShowBrainSourcesResponse.Historical: ...
    def __init__(
        self,
        *,
        voice_memo: global___OpsTicketShowBrainSourcesResponse.VoiceMemo | None = ...,
        sop: global___OpsTicketShowBrainSourcesResponse.Sop | None = ...,
        historical: global___OpsTicketShowBrainSourcesResponse.Historical | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_historical", b"_historical", "_sop", b"_sop", "_voice_memo", b"_voice_memo", "historical", b"historical", "sop", b"sop", "voice_memo", b"voice_memo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_historical", b"_historical", "_sop", b"_sop", "_voice_memo", b"_voice_memo", "historical", b"historical", "sop", b"sop", "voice_memo", b"voice_memo"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_historical", b"_historical"]) -> typing.Literal["historical"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sop", b"_sop"]) -> typing.Literal["sop"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_voice_memo", b"_voice_memo"]) -> typing.Literal["voice_memo"] | None: ...

global___OpsTicketShowBrainSourcesResponse = OpsTicketShowBrainSourcesResponse
