# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from loopos.v1 import loopos_pb2 as loopos_dot_v1_dot_loopos__pb2

GRPC_GENERATED_VERSION = '1.64.3'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in loopos/v1/loopos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class OpsTicketMethodsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/loopos.v1.OpsTicketMethods/Create',
                request_serializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketCreateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Triage = channel.unary_unary(
                '/loopos.v1.OpsTicketMethods/Triage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AcknowledgeDispatch = channel.unary_unary(
                '/loopos.v1.OpsTicketMethods/AcknowledgeDispatch',
                request_serializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketAcknowledgeDispatchRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DispatchWithEscalation = channel.unary_unary(
                '/loopos.v1.OpsTicketMethods/DispatchWithEscalation',
                request_serializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketDispatchWithEscalationRequest.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketDispatchWithEscalationResponse.FromString,
                _registered_method=True)
        self.ProposeNewRule = channel.unary_unary(
                '/loopos.v1.OpsTicketMethods/ProposeNewRule',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketProposeNewRuleResponse.FromString,
                _registered_method=True)
        self.ShowBrainSources = channel.unary_unary(
                '/loopos.v1.OpsTicketMethods/ShowBrainSources',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketShowBrainSourcesResponse.FromString,
                _registered_method=True)


class OpsTicketMethodsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Triage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeDispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchWithEscalation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeNewRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowBrainSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpsTicketMethodsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketCreateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Triage': grpc.unary_unary_rpc_method_handler(
                    servicer.Triage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AcknowledgeDispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeDispatch,
                    request_deserializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketAcknowledgeDispatchRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DispatchWithEscalation': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchWithEscalation,
                    request_deserializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketDispatchWithEscalationRequest.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketDispatchWithEscalationResponse.SerializeToString,
            ),
            'ProposeNewRule': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeNewRule,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketProposeNewRuleResponse.SerializeToString,
            ),
            'ShowBrainSources': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowBrainSources,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.OpsTicketShowBrainSourcesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loopos.v1.OpsTicketMethods', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loopos.v1.OpsTicketMethods', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpsTicketMethods(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.OpsTicketMethods/Create',
            loopos_dot_v1_dot_loopos__pb2.OpsTicketCreateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Triage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.OpsTicketMethods/Triage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeDispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.OpsTicketMethods/AcknowledgeDispatch',
            loopos_dot_v1_dot_loopos__pb2.OpsTicketAcknowledgeDispatchRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchWithEscalation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.OpsTicketMethods/DispatchWithEscalation',
            loopos_dot_v1_dot_loopos__pb2.OpsTicketDispatchWithEscalationRequest.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.OpsTicketDispatchWithEscalationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeNewRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.OpsTicketMethods/ProposeNewRule',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.OpsTicketProposeNewRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowBrainSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.OpsTicketMethods/ShowBrainSources',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.OpsTicketShowBrainSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserMethodsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestTextMessage = channel.unary_unary(
                '/loopos.v1.UserMethods/IngestTextMessage',
                request_serializer=loopos_dot_v1_dot_loopos__pb2.UserIngestTextMessageRequest.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.UserIngestTextMessageResponse.FromString,
                _registered_method=True)
        self.IngestVoiceNote = channel.unary_unary(
                '/loopos.v1.UserMethods/IngestVoiceNote',
                request_serializer=loopos_dot_v1_dot_loopos__pb2.UserIngestVoiceNoteRequest.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.UserIngestVoiceNoteResponse.FromString,
                _registered_method=True)
        self.ListTickets = channel.unary_unary(
                '/loopos.v1.UserMethods/ListTickets',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.UserListTicketsResponse.FromString,
                _registered_method=True)
        self.QueryBrain = channel.unary_unary(
                '/loopos.v1.UserMethods/QueryBrain',
                request_serializer=loopos_dot_v1_dot_loopos__pb2.UserQueryBrainRequest.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.UserQueryBrainResponse.FromString,
                _registered_method=True)
        self.LiveState = channel.unary_unary(
                '/loopos.v1.UserMethods/LiveState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=loopos_dot_v1_dot_loopos__pb2.UserLiveStateResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/loopos.v1.UserMethods/Create',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class UserMethodsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestTextMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestVoiceNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTickets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserMethodsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestTextMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTextMessage,
                    request_deserializer=loopos_dot_v1_dot_loopos__pb2.UserIngestTextMessageRequest.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.UserIngestTextMessageResponse.SerializeToString,
            ),
            'IngestVoiceNote': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestVoiceNote,
                    request_deserializer=loopos_dot_v1_dot_loopos__pb2.UserIngestVoiceNoteRequest.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.UserIngestVoiceNoteResponse.SerializeToString,
            ),
            'ListTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTickets,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.UserListTicketsResponse.SerializeToString,
            ),
            'QueryBrain': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryBrain,
                    request_deserializer=loopos_dot_v1_dot_loopos__pb2.UserQueryBrainRequest.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.UserQueryBrainResponse.SerializeToString,
            ),
            'LiveState': grpc.unary_unary_rpc_method_handler(
                    servicer.LiveState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=loopos_dot_v1_dot_loopos__pb2.UserLiveStateResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loopos.v1.UserMethods', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loopos.v1.UserMethods', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserMethods(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestTextMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.UserMethods/IngestTextMessage',
            loopos_dot_v1_dot_loopos__pb2.UserIngestTextMessageRequest.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.UserIngestTextMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestVoiceNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.UserMethods/IngestVoiceNote',
            loopos_dot_v1_dot_loopos__pb2.UserIngestVoiceNoteRequest.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.UserIngestVoiceNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.UserMethods/ListTickets',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.UserListTicketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.UserMethods/QueryBrain',
            loopos_dot_v1_dot_loopos__pb2.UserQueryBrainRequest.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.UserQueryBrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiveState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.UserMethods/LiveState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            loopos_dot_v1_dot_loopos__pb2.UserLiveStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loopos.v1.UserMethods/Create',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
